# Configuration for ${project.name}
#
# Version: $[project.version}

plugin-prefix: '&cFirst Death &8>> '
debug-enabled: false

# Automatic saving
auto-save:
  enabled: true
  # in seconds
  interval: 300

# Where the plugin won't work.
disabled-worlds:
  - some_random_world

# Keep inventory and exp on fist death?
keep-inventory: true
keep-exp: true

# Deny item and exp drops?
deny-drops: true

# Rewards given to player upon death
rewards:
  inform:
    - "&7You died. You're incompetent. Basically useless when the only purpose was to &2&osurvive&7... "
    - "&7But we'll give you one more chance... just so you know we're the &e&onice guys &7here."
    - "&7Now live and &c&odon't die &7again you &e&odipshit."
  # Add prefix p! to run a command for player.
  # op! to run command for player with OP
  # Add prefix rand! to multiple commands to pick one of them.
  #commands:
    #- 'say Run a command!'
    #- 'p! say I died lol.'
  broadcast:
    - "&f%player% &7died for the first time, what a loser."
  # Vault money
  #money: 100
  # TokenManager tokens
  #tokens: 10
  # Items
  #items:
    #type: DIAMOND
    #name: '&3Little diamond'
    #lore:
      #- '&7Given to &f%player% &7for his first death.'
    #glow: false
